spring:
  application:
    name: edutechapi
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/edutech}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  public:
    key: "classpath:app.pub"
  private:
    key: "classpath:app.key"

logging:
  level:
    root: "INFO"
    org:
      springframework:
        security: "WARN"
        web: "WARN"
      hibernate: "WARN"
    com:
      edutech:
        api: "DEBUG"
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){faint} %clr([%thread]){blue} %clr(%-5level){highlight} %clr(%logger{36}){cyan} - %msg%n"